### ISSUE TITLE
conflict with package hal

### ISSUE THREAD

**Issue by rfherrerac** [idiazst/survdr#1]
When I tried to install a conflict came up: 

Skipping 1 packages not available: hal
Installing 1 packages: hal
Error: (converted from warning) package ‘hal’ is not available (for R version 3.5.3)

R version 3.5.3 (2019-03-11) -- "Great Truth"
Platform: x86_64-apple-darwin15.6.0 (64-bit)

**Comment by idiazst** [comment]
Thanks! I fixed this in https://github.com/idiazst/survdr/commit/9eb7d8befab80b34abce3649eca8cccd71820f92, should work now.
